enum WebApiMethod{
  GetDeptModOrderQualityWithValue,
  Update_UserQualityTracking_Detail,
  Get_CalcuatedTasnifControl,
  StartQualityDepartmentTest,
  CloseQualityDepartmentTest,
  Get_FinalOrderSizeColorDetails,
  Get_AQLOrderSizeColorDetails,
  Set_Size_Measurement_Allowance,
  Set_UserQualityAQLControl,
  Get_Size_Measurement_Allowance,
  Generate_QualityModelOrder_Tracking,
  Get_AQLModelOrderTracking,
  Get_RecycleSizeList,
  SetFull_User_QualityTracking_Detail,
  Delete_QualityInlineError,
  Set_QualityInlineError,
  Get_ModelOrderSizes_CuttingControl,
  DeletePastal_Cutting_Parti,
  Get_Pastal_Cutting_Parti,
  Set_CreatePastal_Cutting_Parti,
  Set_User_QualityTracking_Dikim,
  Get_EmployeesByOperation,
  Get_Quality_Items_WithValue,
  Set_UserQualityFinalControl,
  Get_Quality_Items,
  Get_Model_Order_Control,
  Get_ModelOrder_Image,
  CloseDikimInlineTur,
  login,
  Get_Language_ResourcesKey,
  CheckUserConnection,
  Get_EmployeeDepartment,
  Get_QualityDepartment_ModelOrder,
  Get_DepartmentModelOrder_QualityTest,
  Get_Criteria_ModelOrder,
  Set_ValidatQualityCriticalQualityTest,
  Get_QualityDept_ModelOrder_Tracking,
  IsUserApprovedCriteriaBefore,
  Set_ReadQualityCriticalQualityTest,
  Get_OrderSizeColorDetails,
  Set_CuttingOrderSizeColorDetails,
  Get_DeptModOrderQuality_Items,
  Set_DeptModOrderQualityItems,
  GetOrCreate_QualityDept_ModelOrder_Tracking,
  Get_CuttingPastalQuality_Items,
  CuttingPastal_ApproveRejectItem,
  CuttingPastal_ReOpenCheckItem,
  Get_Quality_ModelOrder_Tracking,
  Get_TasnifControlGroups,
  Create_QualityDept_ModelOrder_Tracking,
  Get_DeptModOrderQualityTest_Items,
  Set_User_QualityTracking_Detail,
  Set_CloseTanifSample,
  Set_TasnifOrderSizeColorDetails,
  Get_Accessory_ModelOrder,
  Set_RegisterCheckAmount,
  GetInlineDikim_QualityDept_ModelOrder_Tracking,
  Get_User_QualityTracking_Detail,
  Generate_DikimInline_Tracking,
  Get_ModelOrderOperation,
  Get_Employees,
  Set_GenerateInlineEmployeeOperation,
  Start_DikimInlineProcess,
  Assign_EmployeeControlAmount,
  CloseEmployeeOperationControlRound,
  Get_Version,
  Get_ModelOrder_Matrix,
  Get_ModelOrderSizes,
  Get_StitchQuality_Items,
  Delete_User_QualityTracking_Detail,
  Get_UserQualityTasnifControl ,
  Set_RecycleUserQualityTasnifControlRec,
  Get_DikimInlineQuality_Items
}


class HttpWebApi{

  final String ApiDomain ="api/";
  final String WebApiDomain = "Quality/";





}