export 'package:itex_soft_qualityapp/Screens/Home/QualityTest/Creteria_Test.dart';
export 'package:itex_soft_qualityapp/Screens/Home/QualityTest/Cutting_Amount.dart';
export 'package:itex_soft_qualityapp/Screens/Home/QualityTest/Cutting_Control.dart';
export 'package:itex_soft_qualityapp/Screens/Home/QualityTest/Cutting_Pastal.dart';
export 'package:itex_soft_qualityapp/Screens/Home/QualityTest/TasnifControl/Tasnif_Control.dart';
export 'package:itex_soft_qualityapp/Screens/Home/QualityTest/Tasnif_Amount.dart';
export 'package:itex_soft_qualityapp/Screens/Home/QualityTest/Accessory_Control.dart';
export 'package:itex_soft_qualityapp/Screens/Home/QualityTest/Dikim_InlineControl/Dikim_InlineControl.dart';
export 'package:itex_soft_qualityapp/Screens/Home/QualityTest/FinalControl/Dikim_LastControl.dart';