plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'flutter'
}

android {
    namespace "com.example.itex_soft_qualityapp"
    compileSdk 33

    defaultConfig {
        applicationId "com.example.itex_soft_qualityapp"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}
